import React, { useState, useEffect } from "react";
import Head from 'next/head';
import { Navbar, Footer } from '.';

const Layout = ({ children, ...props }) => {
    const [darkMode, setDarkMode] = useState(false);

    useEffect(() => {
        window.matchMedia('(prefers-color-scheme: dark)')
            .addEventListener('change', event => {
                event.matches ? setDarkMode(true) : setDarkMode(false);
            });
    }, []);

    useEffect(() => {
        const darkThemeMq = window.matchMedia("(prefers-color-scheme: dark)");
        darkThemeMq.matches ? setDarkMode(true) : setDarkMode(false)
    }, []);

    const onDarkMode = () => {
        setDarkMode(!darkMode);
    };

    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>React Portfolio</title>
                <meta name="description" content="Generated by Ahmet Topal" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='md:min-h-screen 2xl:min-h-screen bg-zinc-100 dark:bg-zinc-800'>
                <Navbar onMode={onDarkMode} darkMode={darkMode} />
                {children}
                <Footer />
            </div>
        </div >
    );
};

export default Layout;