import React, { useState } from "react";
import Head from 'next/head';
import { Navbar, Footer } from '.';

const Layout = ({ children, ...props }) => {
    const [darkMode, setDarkMode] = useState(false);

    const onDarkMode = () => {
        setDarkMode(!darkMode);
    };

    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>React Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='md:min-h-screen 2xl:min-h-screen bg-zinc-100 dark:bg-zinc-800'>
                <Navbar onMode={onDarkMode} darkMode={darkMode} />
                {children}
            </div>
            <Footer />
        </div >
    );
};

export default Layout;