import { useState } from "react";
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Navbar, Footer, Greetings, Skills } from '../components';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const onDarkMode = () => {
    setDarkMode(!darkMode);
    console.log(darkMode);
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>React Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-5 dark:bg-slate-600'>
        <section className='md:min-h-screen 2xl:min-h-max'>
          <Navbar onMode={onDarkMode} />
          <Greetings />
        </section>
        <section className='flex justify-center'>
          <Skills />
        </section>
      </main>

      <Footer />
    </div >
  )
}
